version: '3'

services:
  web:
    build: .
    image: mikedougherty/howmanywinsdoesbrucebochyhave
    ports:
      - "5000"
    environment:
      - HTTPS_METHOD=redirect
      - LETSENCRYPT_HOST=howmanywinsdoesbrucebochyhave.com
      - NGINX_HOST=howmanywinsdoesbrucebochyhave.com
      - VIRTUAL_HOST=howmanywinsdoesbrucebochyhave.com
      - BCH_RECEIVE=qp6nzcx7lx8rcqp8nmtum44lyz6y6zsquc4958amrg
      - BTC_RECEIVE=1NYKhsdb6gxebFXcv4ews7J6L6aBRR8RNi
