---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: howmanywins-cert
  namespace: howmanywins
spec:
  dnsNames:
    - howmanywinsdoesbrucebochyhave.com
    - www.howmanywinsdoesbrucebochyhave.com
